### ISSUE TITLE
To peerDep or not to peerDep

### ISSUE THREAD

**Issue by Swaagie** [terinjokes/assume-sinon#1]
Raising this to an issue as @indexzero, @3rd-Eden and I had a little discussion about having sinon and assume as peerDependencies and how they are sometimes a bit rough/suck. Currently, the project is using modules as devDeps, do we want to use deps or peerDeps? I personally feel that peerDeps are the 'proper' way of handling the sinon and assume dependencies.

**Comment by terinjokes** [comment]
I'm not a fan of peerDependencies, and currently this code doesn't have any dependency on `sinon` or `assume` at all, except in the tests.

**Comment by indexzero** [comment]
I agree with @terinjokes. We should not peerDep.

**Comment by Swaagie** [comment]
Since npm is moving away from peerDep as well this makes sense, lets keep it like it is
